name: Build All Platforms (No Sign)

on:
  workflow_dispatch: # 手动触发

jobs:
  # 打包 Android, iOS, Mac
  build-mac-ios-android:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      # 1. 签出代码 (改为 master 分支，如果是 dev 分支请自行修改)
      - uses: actions/checkout@v4
        with:
          ref: master

      # 2. 设置 JAVA 环境
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      # 3. 设置 Flutter (使用 3.38 解决依赖问题)
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          channel: 'master' 
          cache: true

      # 4. 开启 Desktop 支持
      - name: Enable Flutter Desktop
        run: flutter config --enable-macos-desktop

      # 5. 拉取依赖
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # 6. 安装工具 (Mac打包需用)
      - name: Install appdmg
        run: npm install -g appdmg
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # ---------------------------------------------------------
      #  ANDROID 部分 (改为 Debug 模式，跳过签名)
      # ---------------------------------------------------------
      - name: Build APK (Debug)
        run: |
          cd simple_live_app
          flutter build apk --debug

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-debug
          path: simple_live_app/build/app/outputs/flutter-apk/app-debug.apk

      # ---------------------------------------------------------
      #  iOS 部分 (免签名模式)
      # ---------------------------------------------------------
      - name: Build IPA (No CodeSign)
        run: |
          cd simple_live_app
          # iOS 必须用 release --no-codesign 才能生成无签名包
          flutter build ios --release --no-codesign

      - name: Create Payload for IPA
        run: |
          cd simple_live_app
          mkdir -p build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r ios_no_sign.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned
          path: simple_live_app/build/ios/iphoneos/ios_no_sign.ipa

      # ---------------------------------------------------------
      #  MacOS 部分
      # ---------------------------------------------------------
      - name: Build MacOS
        run: |
          cd simple_live_app
          flutter_distributor package --platform macos --targets dmg,zip --skip-clean

      - name: Upload MacOS
        uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: |
            simple_live_app/build/dist/*/*.dmg
            simple_live_app/build/dist/*/*.zip

  # 打包 Windows (独立任务)
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          channel: 'master'
          cache: true
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop
      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub get
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor
      
      - name: Build Windows
        run: |
          cd simple_live_app
          flutter_distributor package --platform windows --targets msix,zip --
